version: '3.8'
services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - .docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
  php:
    build:
      context: .docker/php
    volumes:
      - .:/var/www/html
